USE openfoodfacts;

CREATE TABLE MARQUE(
Id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
nom VARCHAR(30)
);

CREATE TABLE CATEGORIE(
Id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
nom VARCHAR(30)
);

CREATE TABLE PRODUIT(
Id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
nom VARCHAR(30),
nutritionGradeFr VARCHAR(1),
energie DECIMAL(16,8),
graisse DECIMAL(16,8),
sucre DECIMAL(16,8),
fibre DECIMAL(16,8),
proteine DECIMAL(16,8),
sel DECIMAL(16,8),
allergenes VARCHAR(30),
additifs VARCHAR(30),
Id_cat INT(11),
Id_marq INT(11),
CONSTRAINT FOREIGN KEY(Id_cat) REFERENCES CATEGORIE(Id),
CONSTRAINT FOREIGN KEY(Id_marq) REFERENCES MARQUE(Id)
);

CREATE TABLE INGREDIENT(
Id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
composition VARCHAR(100),
Id_prd INT(11),
CONSTRAINT FOREIGN KEY(Id_prd) REFERENCES PRODUIT(Id)
);
/*
ALTER TABLE PRODUIT ADD CONSTRAINT FOREIGN KEY(ID_CAT) REFERENCES CATEGORIE(Id);
ALTER TABLE PRODUIT ADD CONSTRAINT FOREIGN KEY(ID_MARQ) REFERENCES MARQUE(Id);*/
